spring.application.name=mvp

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/patas_sem_lar
spring.datasource.username=postgres
spring.datasource.password=my_secure_dev_password

# Using validate and not create
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway - Auto-runs migrations on startup
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration
