"""service_canonical_and_offering_overrides

Revision ID: 12af6908b4fc
Revises: 18a779368dd3
Create Date: 2026-05-14 09:13:27.097432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12af6908b4fc'
down_revision: Union[str, Sequence[str], None] = '18a779368dd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('professional_id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('default_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('offerings', sa.Column('service_id', sa.String(length=26), nullable=False))
    op.add_column('offerings', sa.Column('price_override', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('offerings', sa.Column('duration_override', sa.Integer(), nullable=True))
    op.add_column('offerings', sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.create_index('ix_offerings_service_link_unique', 'offerings', ['service_id', 'professional_store_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_foreign_key(None, 'offerings', 'services', ['service_id'], ['id'])
    op.drop_column('offerings', 'price')
    op.drop_column('offerings', 'name')
    op.drop_column('offerings', 'duration_minutes')
    op.drop_column('offerings', 'description')
    op.drop_column('offerings', 'is_active')
    op.drop_constraint(op.f('professional_invites_token_key'), 'professional_invites', type_='unique')
    op.drop_index(op.f('ix_professional_invites_token'), table_name='professional_invites')
    op.create_index(op.f('ix_professional_invites_token'), 'professional_invites', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_professional_invites_token'), table_name='professional_invites')
    op.create_index(op.f('ix_professional_invites_token'), 'professional_invites', ['token'], unique=False)
    op.create_unique_constraint(op.f('professional_invites_token_key'), 'professional_invites', ['token'], postgresql_nulls_not_distinct=False)
    op.add_column('offerings', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('offerings', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('offerings', sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('offerings', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('offerings', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'offerings', type_='foreignkey')
    op.drop_index('ix_offerings_service_link_unique', table_name='offerings', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_column('offerings', 'is_enabled')
    op.drop_column('offerings', 'duration_override')
    op.drop_column('offerings', 'price_override')
    op.drop_column('offerings', 'service_id')
    op.drop_table('services')
    # ### end Alembic commands ###
